### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/BiomeRemap#1]
**Description**
Beginning with Spigot 1.15.2 (Jenkins 2596), missing dependency declarations are reported in the log on server start-up as WARN messages.

Reference: [https://hub.spigotmc.org/jira/browse/SPIGOT-5546](https://hub.spigotmc.org/jira/browse/SPIGOT-5546)

The relevant log entry is:
```
[22:04:11] [Server thread/WARN]: [BiomeRemap] Loaded class me.clip.placeholderapi.expansion.PlaceholderExpansion from PlaceholderAPI v2.10.5-DEV-84 which is not a depend, softdepend or loadbefore of this plugin.
```

**Reproduction steps**
- Update Spigot to 1.15.2 latest
- Start the server
- Search the log for 'Loaded class'

**Expected behavior**
Dependencies should be declared in plugin.yml

**Server Environment**
 - Spigot version [/version]: 1.15.2 (Jenkins 2596)
 - BiomeRemapper version [/version BiomeRemapper]: 2.0.2

**Comment by mart-r** [comment]
You're right. I've neglected to declare PlaceholderAPI as a dependency in plugin.yml.

I will fix that tonight (in 13-14h).

I suppose it'd be fair to release it as 2.0.3 then.

**Comment by SlimeDog** [comment]
Yep. :)
No hurry. There are 36 plugins in my test bed that have similar issues, every one more important than BiomeRemap.
