### ISSUE TITLE
Feature request: Support biome remapping in entire chunk column

### ISSUE THREAD

**Issue by iperrealistico** [SlimeDog/BiomeRemap#3]
**Description**
Biome name and grass colour do not change, but as expected, it starts snowing

**Reproduction steps**
Use the plugin on a fresh git-Paper-331 (MC: 1.16.4) server

**Expected behavior**
Biome name should change from savannah to snowy tundra
![image](https://user-images.githubusercontent.com/25549272/102624340-25a3b780-4144-11eb-9b91-dccbbebdc561.png)

**Screenshots**
Look at the biome name and grass colour... it's snowing tho
![image](https://user-images.githubusercontent.com/25549272/102624374-318f7980-4144-11eb-923d-8e4f81563a1d.png)

**Server Environment**
 - OS [Linux, MacOS, Windows] version: testing serve ron Windows 10
 - Spigot version [/version]: git-Paper-331 (MC: 1.16.4) server
 - BiomeRemap version [/version BiomeRemap]: BiomeRemap version 2.1.7

**Additional context**
 Link to your configuration: stock config with my world name added to it
 Link to error log: no errors

**Comment by SlimeDog** [comment]
Please note (from the [Overview page](https://www.spigotmc.org/resources/biomeremap.70973/)):
```
BiomeRemap will not be backported to support previous Spigot releases or non-Spigot variants; please don't ask.
```
However ...

The snow suggests that the biome has actually changed, but is reported incorrectly in the HUD. Suggestion: disconnect/reconnect and verify the biome. Please include the location in the next screenshot.

**Comment by iperrealistico** [comment]
>  non-Spigot variants
oh no, I completely missed that part of the sentence! That's terrible news since spigot's terrain generation is actually unusable on small-medium scale servers, or when you want to pregenerate large chunks of a world! 😢 

Restarted server and relogged

![image](https://user-images.githubusercontent.com/25549272/102632894-f7c47000-414f-11eb-9179-7431c156e7b0.png)

If I do /biomeremap scan chunk World 15 6 1
The plugin actually thinks it has been remapped, but, visually, it's not

![image](https://user-images.githubusercontent.com/25549272/102633037-322e0d00-4150-11eb-8521-1a2a50d6abd6.png)

If you are into porting this to support paper I would 100% love to contribute with a donation 😄 Would make the plugin actually usable in a lot more scenarios

**Comment by SlimeDog** [comment]
Thanks for the complete report. That is helpful. Since snow is falling and sticking to the ground, I would say that the in-game visuals are fine. Unfortunately, the HUD is incorrectly reporting the original biome.

I cannot personally support Paper, but I will discuss the issue with the dev.

**Comment by iperrealistico** [comment]
> Thanks for the complete report. That is helpful. Since snow is falling and sticking to the ground, I would say that the in-game visuals are fine. Unfortunately, the HUD is incorrectly reporting the original biome.
> 
> I cannot personally support Paper, but I will discuss the issue with the dev.

Also the grass color is sticking to the value the HUD is saying. And that's the top reason I would love to use the plugin for.. changing grass color 😃 

I am expanding my servers map switching the generator to OldGenerator to generate old beta 1.7.3 chunks, and the problem is that some ugly biomes that did not exist do generate in the newly expanded map, tinting grass color without actually adding biome specific features. 

I would love to remap those non-implemented biomes to the good old plains, or something that existed back in 1.7.3

**Comment by SlimeDog** [comment]
It would have been good if you had mentioned [OldGenerator](https://www.spigotmc.org/resources/oldgenerator-1-16-4.86600/) earlier. Please confirm that this issue exists on Paper without [OldGenerator](https://www.spigotmc.org/resources/oldgenerator-1-16-4.86600/). If it does, please provide the world seed, so we can verify.

**Comment by iperrealistico** [comment]
Of course I am testing the plugin without having OldGenerator enabled, the issue still applies to the vanilla world gen (seed: 69160882195)

![image](https://user-images.githubusercontent.com/25549272/102657302-ba72d900-4175-11eb-8a23-f879fc25ba82.png)

![image](https://user-images.githubusercontent.com/25549272/102657364-d4142080-4175-11eb-9b6a-286968970454.png)

![image](https://user-images.githubusercontent.com/25549272/102657381-db3b2e80-4175-11eb-910a-9aa6c800021b.png)

**Comment by SlimeDog** [comment]
OK, thanks.

**Comment by SlimeDog** [comment]
This seems to be a problem related to the new 3D biomes. The "controlling" biome is correct -- thus the snow -- but the "visible" biome is not. This occurs in both Spigot and Paper. We will review. Thanks for the report.

**Comment by mart-r** [comment]
I've pushed some changes to another branch that (I think) fix the issues.
What it does is effectively change the biomes for all other layers as well, even though from a game mechanics point of view, only the biome at the very bottom of the world seems to matter.

With that said, here's the branch:
https://github.com/SlimeDog/BiomeRemap/tree/biomeCheck
And here's the download link:
https://www.dropbox.com/s/wst9erd82lrdcho/BiomeRemap-2.1.8-SNAPSHOT.jar?dl=0

Let me know if this fixes the issue and/or if it produces other issues.

**Comment by iperrealistico** [comment]
Honestly I was thinking about 3D biomes too, because they have been introduced recently and it looked like the plugin was acting only on a layer and not on the entire chunk 😁

Testing on Paper, loading chunks flying over them - **it's working**

Testing on Paper, generating chunks using Fast Chunk Pregenerator (uses async paper gen system) - **seems to be working**

Testing on Paper, with OldGenerator by Spottedleaf - unfortunately, looks like it's not working

/biomeremap scan chunk tells me the desert chunk is 100% snowy tundra, but, unfortunately, it's still desert.. it does not even snow

You did an awesome job so far, it's very cool to see savannahs with blue tinted grass! Unfortunately looks like I can't use the plugin for my map expansion plan, unless you are into adding support for (at least) OldGenerator. If you are interested, it's on github.

https://www.spigotmc.org/resources/oldgenerator-1-16-4.86600/
https://github.com/Spottedleaf/OldGenerator

Anyways I wanted to donate you a pizza. Well, it depends on how pricy pizzas are where you live. Split it in half, for both of you lol

**Comment by SlimeDog** [comment]
Thanks for the detailed feedback. I will confirm later -- the complete test protocol takes half a day.

> Testing on Paper, generating chunks using Fast Chunk Pregenerator (uses async paper gen system) - seems to be working

BiomeRemap works with both pregenerators I tested on Spigot 1.16.4: WorldBorder and Chunky. Nice to know that it seems to work with FCP on Paper.

> /biomeremap scan chunk tells me the desert chunk is 100% snowy tundra, but, unfortunately, it's still desert.. it does not even snow

Desert should still work. I'll have to take a look. Note that sometimes one has to disconnect/reconnect, and sometimes move to a different area and back, for MC to respond properly.

> Unfortunately looks like I can't use the plugin for my map expansion plan, unless you are into adding support for (at least) OldGenerator. If you are interested, it's on github.

OldGenerator is outside the scope of BiomeRemap. If you want to take a stab at it, I would review a PR, but I cannot justify spending resources on research and development.

> Anyways I wanted to donate you a pizza. Well, it depends on how pricy pizzas are where you live. Split it in half, for both of you lol

Thanks for the donation -- very much appreciated. It is my practice to split donations with the devs. Unfortunately, we can do so only virtually, since we live on different continents. :(

**Comment by SlimeDog** [comment]
> I've pushed some changes to another branch that (I think) fix the issues.
> What it does is effectively change the biomes for all other layers as well, even though from a game mechanics point of view, only the biome at the very bottom of the world seems to matter.
> 
> With that said, here's the branch:
> https://github.com/SlimeDog/BiomeRemap/tree/biomeCheck
> And here's the download link:
> https://www.dropbox.com/s/wst9erd82lrdcho/BiomeRemap-2.1.8-SNAPSHOT.jar?dl=0
> 
> Let me know if this fixes the issue and/or if it produces other issues.

The change is pretty minimal. But I'm not sure that it is desirable. Personally, I like that the visible biome is the original, but with snow. There are quite a few advantages to that, but I understand that others would prefer the other way. Perhaps this change should be filtered by a configuration option. Let's discuss.

**Comment by SlimeDog** [comment]
> Note that sometimes one has to disconnect/reconnect, and sometimes move to a different area and back, for MC to respond properly.

That is the case, confirmed on Spigot and Paper. When I returned to the desert location, there was snow falling and on the ground. Mart, is there anything we can do about it?

**Comment by SlimeDog** [comment]
Hmmm.
```
		int yNr = nr;
 		for (int y = 0; y < 63; y++) {
 			yNr += 16;
 			bases[yNr] = nmsBiomeBase;
 		}
```
63 * 16 = 1006, which is well above the ceiling=255. Is that intended?

**Comment by iperrealistico** [comment]
> Desert should still work. I'll have to take a look. Note that sometimes one has to disconnect/reconnect, and sometimes move to a different area and back, for MC to respond properly.

Yeah restarted the server and now seems to be working! Amazing

> Thanks for the donation -- very much appreciated. It is my practice to split donations with the devs. Unfortunately, we can do so only virtually, since we live on different continents. :(

Or send half a rotten pizza to another continent lol

Anyways, ill keep you informed with any other eventual bug i find out

**Comment by mart-r** [comment]
> > I've pushed some changes to another branch that (I think) fix the issues.
> > What it does is effectively change the biomes for all other layers as well, even though from a game mechanics point of view, only the biome at the very bottom of the world seems to matter.
> > With that said, here's the branch:
> > https://github.com/SlimeDog/BiomeRemap/tree/biomeCheck
> > And here's the download link:
> > https://www.dropbox.com/s/wst9erd82lrdcho/BiomeRemap-2.1.8-SNAPSHOT.jar?dl=0
> > Let me know if this fixes the issue and/or if it produces other issues.
> 
> The change is pretty minimal. But I'm not sure that it is desirable. Personally, I like that the visible biome is the original, but with snow. There are quite a few advantages to that, but I understand that others would prefer the other way. Perhaps this change should be filtered by a configuration option. Let's discuss.

Yeah, an option sounds like a good idea.

> > Note that sometimes one has to disconnect/reconnect, and sometimes move to a different area and back, for MC to respond properly.
> 
> That is the case, confirmed on Spigot and Paper. When I returned to the desert location, there was snow falling and on the ground. Mart, is there anything we can do about it?

I'm keeping track of people teleporting and that causing remaps. And in that case, the updated biome information is sent to the client. That is, I'm caching the players that have teleported and if a chunk within view distance from them is remapped, then an update will be sent (within 1 second, it's an undocumented config entry `teleport-cache-time-ticks`). So that should cover most of the cases.
If there's some cases that I've missed, It'd be appreciated if someone could describe the situation in which this happens in more detail.



> Hmmm.
> 
> ```
> 		int yNr = nr;
>  		for (int y = 0; y < 63; y++) {
>  			yNr += 16;
>  			bases[yNr] = nmsBiomeBase;
>  		}
> ```
> 
> 63 * 16 = 1006, which is well above the ceiling=255. Is that intended?

There are a total of 1024 biome information slots now. It was 256 before 1.16.

**Comment by SlimeDog** [comment]
> Yeah, an option sounds like a good idea.

OK, I will construct an option description and node-name.

> If there's some cases that I've missed, It'd be appreciated if someone could describe the situation in which this happens in more detail.

I wil try to produce a reproducible recipe.

> There are a total of 1024 biome information slots now. It was 256 before 1.16.

Ah. But we are adjusting only every 16th one, presumably one per vertical chunk. Is that it? And that is sufficient?

**Comment by mart-r** [comment]
> Ah. But we are adjusting only every 16th one, presumably one per vertical chunk. Is that it? And that is sufficient?

Yeah, that should be sufficient. That should mean that we're updating all biomes above a specific point. If all biomes within a chunk are remapped, all 1024 biomes will be changed, but 64 at a time (for each of the 16 sections on the horizontal plane that are 4x4).

**Comment by SlimeDog** [comment]
Proposed configuration additions, offered for discussion. Please review for accuracy and clarity. And suggestions are requested for a more descriptive node name.
```
# biomemaps:
#   NAME:
#     description: TEXT
#     enabled-worlds: LIST
#     full-chunk-remap: TRUE|FALSE (default:FALSE)
#     biomes:
#        BIOME_ENUM:
#         replacement-biome: BIOME_ENUM
```
```
# biomeremap.NAME.full-chunk-remap
#   * Prior to MC 1.16.2, "chunk" referred to a 16x16 column, across all Y values; the biome of the 
#     entire column was specified by a single BIOME_ENUM value in the base chunk (Y=0).
#   * Starting with MC 1.16.2, "chunk" refers to a 16x16x16 cube; the biome of each cubic chunk may 
#     be specified independently. BiomeRemap addresses this change in the following way:
#        * biomeremap.NAME.full-chunk-remap: FALSE (default)
#          Only the base chunk (Y=0) will be remapped. This changes weather (for example, rain vs.
#          snow) in the entire column, but changes the visual characteristics (for example, grass
#          color) in the base chunk only. So the surface terrain characteristics remain unchanged.
#        * biomeremap.NAME.full-chunk-remap: TRUE
#          The entire column will be remapped. This changes weather in the same way, but changes the
#          the visual characteristics of the entire column. So the surface terrain characteristics
#          will reflect the new biome.
#   * WARNING: The configuration should be changed only after careful consideration and testing. The
#     consequences of TRUE cannot be reversed, except by regenerating chunks after reverting to FALSE.
```

**Comment by iperrealistico** [comment]
Yup the config option is easily understandable and it's quite useful for other use cases that are not the one I needed the plugin for this time. Maybe add a note that setting to true can increase the computational cost since you need to loop all the chunk biome areas? (If it does)

**Comment by SlimeDog** [comment]
> Maybe add a note that setting to true can increase the computational cost since you need to loop all the chunk biome areas? (If it does)

How about:
```
#        * biomeremap.NAME.full-chunk-remap: TRUE
#          The entire column will be remapped. This changes weather in the same way, but changes the
#          the visual characteristics of the entire column, so the surface terrain characteristics
#          will reflect the new biome. This will incur a small additional computational cost to loop
#          through the entire column, but it should not be noticeable in practice, and will not affect
#          game play if the chunks are pre-generated (which we recommend in any event).
```

**Comment by mart-r** [comment]
Works for me.

Let me know if/when you want me to implement it fully.

**Comment by SlimeDog** [comment]
Let me do more comparison testing first. I'll let you know.

**Comment by SlimeDog** [comment]
I posted updates to config.yml in master.

**Comment by SlimeDog** [comment]
2.1.9-c tests successfully. Please update master and build for final testing and release.

**Comment by SlimeDog** [comment]
Optional feature added in version 2.2.0 for Spigot and Paper 1.16.4.

The feature and options are described in the _config.yml_ comments, and in the [update notification](https://www.spigotmc.org/resources/biomeremap.70973/update?update=377562).
