### ISSUE TITLE
Problems with overriding biomes

### ISSUE THREAD

**Issue by ErythroCraft** [SlimeDog/BiomeRemap#7]
**Description**
I installed your plugin and created any overrides in the config file.
But nothing is happen.

**Reproduction steps**
1. install the plugin
2. edit config file
3. start server
4. create world with /mv create [world name] normal
5. your plugin was not exeptable the config

**Expected behavior**
Editing config file to override biomes

**Server Environment**
 - OS [Linux, MacOS, Windows] version: **Windows 10**
 - Java version [java -version]: **Java 17**
 - Server version [/version]: **Spigot 1.18**
 - BiomeRemap version [/version BiomeRemap]: 3.0.0

**Additional context**
 Link to your configuration: 
[config.zip](https://github.com/SlimeDog/BiomeRemap/files/7920728/config.zip)

 Link to error log:
[2022-01-23-3.log.gz](https://github.com/SlimeDog/BiomeRemap/files/7920730/2022-01-23-3.log.gz)

What is the misstake and how can I use your plugin correctly?

**Comment by SlimeDog** [comment]
Thanks for the detailed information.

The errors are shown in the log above. The names of biomes must be spelled correctly. The `config.yml` above contains several errors:
```
[15:46:49] [Server thread/ERROR]: [BiomeRemap] Biome old_growth_pain_taiga does not exist
[15:46:49] [Server thread/ERROR]: [BiomeRemap] Biome bambooo_jungle does not exist
[15:46:49] [Server thread/ERROR]: [BiomeRemap] Biome savana does not exist
[15:46:49] [Server thread/ERROR]: [BiomeRemap] Biome old_growth_pain_taiga does not exist
[15:46:49] [Server thread/ERROR]: [BiomeRemap] Biome old_growth_pain_taiga does not exist
```
Correct the configuration to use
```
old_growth_pine_taiga
bamboo_jungle
savanna
```
as contained in the original `config.yml` or listed in the [Wiki Configuration](https://github.com/SlimeDog/BiomeRemap/wiki/Biomes).

Please confirm that the issue is resolved.

**Comment by ErythroCraft** [comment]
This was helping to load the config and set it to the worlds.
Thanks for first steps.

**Description**
Any biomes will not working.

**Reproduction steps:**

using /mv regen HighLand -s

**RESULT:**
Watch out the pictures:

**1. plains should overridden by snowy_plains**
![2022-01-23_18 25 28](https://user-images.githubusercontent.com/76217862/150690309-a6354441-a605-4993-9b92-ae1351f6c3db.png)


**2. oceans should overriden by stony_peaks and stony_shore**
![2022-01-23_18 24 36](https://user-images.githubusercontent.com/76217862/150690313-08c5c00d-f728-4ee0-9c6b-5e08868330ec.png)


config file:
[config.zip](https://github.com/SlimeDog/BiomeRemap/files/7921009/config.zip)

**Comment by SlimeDog** [comment]
The pictures do not show biome assignments.
- Use `bmap scan chunk` in-game to show the biome assignments for the current chunk
-  Use `bmap chunk` in-game to remap the current chunk

**Comment by ErythroCraft** [comment]
this is not working.

**Comment by SlimeDog** [comment]
I don't know how to respond to "this is not working". More details are needed for us to analyze. May I join your test server?

**Comment by ErythroCraft** [comment]
I used the commands and the result is nothing.

I don't no how I can fix this.
So, I understood the commands will recreate the chunks

Watch out the video:
https://user-images.githubusercontent.com/76217862/150692627-2b6ebaef-be9a-47c1-bb11-138f87fa51e6.mp4

**Comment by SlimeDog** [comment]
`bmap chunk` does not recreate the chunk. It changes the biome of the chunk. It would be really helpful to join your test server to see what is happening.

BTW, the MP4 does not load.

**Comment by ErythroCraft** [comment]
Name
TestServer2

Server Address 
[address elided]

**Comment by ErythroCraft** [comment]
Thank you very much to help me understand the plugin.

The issue is resolved.
